apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tester
  name: tester
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tester
status:
  loadBalancer: {}
