apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tester-role
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tester-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tester-role
subjects:
- kind: ServiceAccount
  name: tester
  namespace: test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tester
  name: tester
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tester
  strategy: {}
  template:
    metadata:
      labels:
        app: tester
    spec:
      serviceAccountName: tester
      containers:
      - image: tester:latest
        name: tester
        args:
        - "main:app"
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        env:
        - name: REQUESTS_CA_BUNDLE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tester
  name: tester
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tester
status:
  loadBalancer: {}